export const CREATE_CHANNEL = 'CREATE_CHANNEL'
export const VIEW_CHANNEL = 'VIEW_CHANNEL'
export const SIGN_IN = 'SIGN_IN'
export const SIGN_OUT = 'SIGN_OUT'
export const HOME = 'HOME'
export const NOT_FOUND = 'NOT_FOUND'
