export const CHANNELS_NEW = 'CHANNELS_NEW'
export const CHANNELS_SHOW = 'CHANNELS_SHOW'
export const SIGN_IN = 'SIGN_IN'
export const SIGN_OUT = 'SIGN_OUT'
export const HOME = 'HOME'
export const NOT_FOUND = 'NOT_FOUND'
